[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.24"
solc-optimizer = true
solc-optimizer-runs = 200
viaIR = true

remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "ds-test/=lib/forge-std/lib/ds-test/src/",
    "forge-std/=lib/forge-std/src/"
    ]

[etherscan]
sepolia = { key = "CBTKPBT7ZHVZ3QEKT761YUTDAFYDUGEUTE", url = "https://api-sepolia.etherscan.io/api" }
scroll-sepolia = { key = "YD4SSI87D8CE61VG5STXQAAWVR2WF8DYPY", url = "https://api-sepolia.scrollscan.com/api" }